# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

WORKSPACE = ENV['WORKSPACE'] || "."

Vagrant.configure(VAGRANTFILE_API_VERSION) do |vagrant|
    vagrant.vm.box = "vetbase/centos-7"

    # set IP address
    vagrant.vm.network "private_network", ip: "192.168.32.14"

    # always use vagrant's insecure key
    vagrant.ssh.insert_key = false

    # virtualbox specific settings
    vagrant.vm.provider "virtualbox" do |v|
        # custom name
        v.name = "vetbase-toolbox-frontend"
    end

    vagrant.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
    end

    # sync src folder
    vagrant.vm.synced_folder WORKSPACE, "/development", create: true
end
